### PR TITLE
esmf v8.7.0

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
This is an alternative to #123 so I can leave that one around to debug the rerender issue I posted on conda-smithy.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

File: recipe/0006-Make-pathtype-recognize-Windows-style-absolute-paths.patch [hunk 1]
```diff
@@ -1,18 +1,9 @@
...
---- a/scripts/pathtype
-+++ b/scripts/pathtype
-@@ -1,8 +1,9 @@
- #!/bin/sh
+diff -ruN --no-dereference esmf-8.7.0/scripts/pathtype esmf-8.7.0-patch/scripts/pathtype
+--- esmf-8.7.0/scripts/pathtype	2024-10-03 21:21:21.000000000 -0600
++++ esmf-8.7.0-patch/scripts/pathtype	2024-10-26 11:50:13.260479971 -0600
+@@ -1,8 +1,10 @@
+-#!/bin/sh
++#!/bin/bash
```
Comment (xylar) [inline recipe/0006-Make-pathtype-recognize-Windows-style-absolute-paths.patch:6]: I believe the new syntax requires bash and not general sh here.  At least it failed for me on Ubuntu.

**Comment by xylar** [comment]
Yep, the rerender messed things up here, too.  So not rerendering for now.

File: recipe/meta.yaml [hunk 2]
```diff
@@ -15,13 +15,13 @@ package:
...
   url: https://github.com/esmf-org/esmf/archive/refs/tags/v{{ version }}.tar.gz
-  sha256: dc270dcba1c0b317f5c9c6a32ab334cb79468dda283d1e395d98ed2a22866364
+  sha256: d7ab266e2af8c8b230721d4df59e61aa03c612a95cc39c07a2d5695746f21f56
   patches:
     # remove these very long running tests only for aarch64 nompi (which is hanging)
     - remove-long-running-tests.patch  # [aarch64 and mpi == 'nompi']
     # Sequence of Windows targeting patches; should be unix compatible
     - 0001-Add-x86_64-machine-id-for-MinGW.gfortran.patch
-    - 0002-Change-long-int-to-long-long-for-Windows-compatibili.patch
+    # - 0002-Change-long-int-to-long-long-for-Windows-compatibili.patch
```
Comment (xylar) [inline recipe/meta.yaml:24]: This one seemed to cause trouble on OSX (64 and ARM).  It may be that I messed up the update on the patch but since we're not building for Windows right now I'm just going to comment it out for now.

Comment (xylar) [reply recipe/meta.yaml:24]: Nope, I spoke too soon.  Same issue without the patch.

**Comment by xylar** [comment]
No luck with external PIO with `mpi_serial`.  Seems like `mpi_serial` and `mpiuni` aren't quite compatible?  Errors like:
```
/home/conda/feedstock_root/build_artifacts/esmf_1729976334318/work/src/Infrastructure/VM/src/ESMCI_VMKernel.C: In member function 'void ESMCI::VMK::finalize(int)':
/home/conda/feedstock_root/build_artifacts/esmf_1729976334318/work/src/Infrastructure/VM/src/ESMCI_VMKernel.C:832:3: error: 'MPI_Finalized' was not declared in this scope; did you mean 'MPI_Finalize'?
  832 |   MPI_Finalized(&finalized);
      |   ^~~~~~~~~~~~~
      |   MPI_Finalize
/
```

**Comment by xylar** [comment]
With the internal PIO, the OSX errors are related to looking for `libnetcdf.so` when it should be looking for `libnetcdf.dynlib`.  I'll look into it...

**Comment by xylar** [comment]
Alright, I think we're all set.  I don't think the rerender that broke stuff in #123 did anything vital so I might merge without rerendering for now.

**Comment by xylar** [comment]
Hmm, it looks like the OSX image changed so I'm going to keep the rerender after all.  I manually changed the permissions back to allow execution on the `.sh` files.

**Comment by xylar** [comment]
@zklaus, @ocefpaf I expect tests to pass at this point.  Let me know if you'd like to have a closer look.  Otherwise, I'll merge tomorrow as long as tests are passing.

File: recipe/meta.yaml [hunk 3]
```diff
@@ -15,7 +15,7 @@ package:
 
 source:
   url: https://github.com/esmf-org/esmf/archive/refs/tags/v{{ version }}.tar.gz
-  sha256: dc270dcba1c0b317f5c9c6a32ab334cb79468dda283d1e395d98ed2a22866364
+  sha256: d7ab266e2af8c8b230721d4df59e61aa03c612a95cc39c07a2d5695746f21f56
   patches:
     # remove these very long running tests only for aarch64 nompi (which is hanging)
     - remove-long-running-tests.patch  # [aarch64 and mpi == 'nompi']
```
Comment (xylar) [inline recipe/meta.yaml:21]: It looks like we might need to add `linux-64` and `ppc64le` with `mpich`.  These now also seem to be hanging.

Comment (xylar) [reply recipe/meta.yaml:21]: Takes awhile but at least linux-64 is moving again.

Comment (xylar) [reply recipe/meta.yaml:21]: Looks like we just need to be patient.
